version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=redesign
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=123
    ports:
      - '5442:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: redesign_api
    ports:
      - 9002:9002
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend

volumes:
  db:
    driver: local

networks:
  backend: