INSERT INTO public.questionnaires ("questionnaires_uuid","category","question","option_type", "comment_type", "created_at", "updated_at")
VALUES
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Number of full-time employees at this location.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Number of freelancers, contractors, and sub-contractors at this location.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Describe the duties of any freelance and sub-contracted staff.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Does your company hire interns?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Is your company at least 51% owned and managed by a Minority, Woman, Veteran or LGBTQ?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Which resources are permitted to work unsupervised past normal or regular business hours?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Are background checks performed on employees and third-party personnel?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Which background checks (education, ID, criminal, etc.) are performed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Who performs background checks (e.g., internal or third party)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Are employees and third-party personnel required to sign non-disclosure agreements?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Are employees and third-party personnel contractually obliged to adhere to client''s security requirements?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Are all third-party services explicitly approved in writing by the client?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Are employees and third-party personnel given security awareness training upon hiring and before being granted access to content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'What are the training topics?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'How often is the training repeated?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'How is the completion of training recorded?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Is anonymous reporting provided to employees and third-party personnel?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'What tools are available for anonymous reporting?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Are job functions segregated to eliminate overlap where possible in the content workflow?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Please provide specific instances of such segregation in content the workflow.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Are employees and third-party personnel issued photo ID?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'How is the use of photo IDs enforced?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'What policies/procedures are in place to monitor third-party personnel access in production areas?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Is there a policy on the use of digital devices (e.g., smartphones, tablets, USB thumb drives, digital cameras, and laptops) in restricted areas?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Please describe the policy.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Is there a policy on posting and sharing (e.g., content, projects) on social media platforms?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Please describe the policy.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Is there a policy on referencing clients on social media platforms?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Please describe the policy.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Is there a policy on posting, sharing, or referencing security or working titles on social media platforms?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Please describe the policy.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'Do you have documentation on exit process for terminated employees and third-party personnel?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Employees and Third-Party Personnel', 'What are the activities and processes involved when employment or contract is terminated?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Risk Management', 'Do you conduct Risk Assessments?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Risk Management', 'What is included and how often is it conducted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Business Continuity Management', 'Do you have a business continuity plan?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Business Continuity Management', 'How is it implemented?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Business Continuity Management', 'How frequently is it tested?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Business Continuity Management', 'How is it maintained and updated?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Organizational Controls', 'Do you have a Security Management Team?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Organizational Controls', 'What are the responsibilities of the Security Management Team?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Organizational Controls', 'Do you have a Security Incident Response Team?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Organizational Controls', 'What are the responsibilities of the Security Incident Response Team?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Management Systems Policies and Procedures', 'Do you have a data breach and incident response policy or process in place?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Management Systems Policies and Procedures', 'What are the conditions to determine if an event is an incident?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Management Systems Policies and Procedures', 'How are your clients informed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Management Systems Policies and Procedures', 'Do you notify law enforcement agencies as part of your incident response?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Management Systems Policies and Procedures', 'Under what circumstances do you notify law enforcement agencies?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'What is the facility size in Sq. Ft.?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'What are the hours of operation?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'Where is the Server / Machine Room located?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'How many employees have access to the machine and/or server room?4', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'Does your facility have a perimeter fence/wall?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'Do you share your building with other companies?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'Do you have electronic access installed within your facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'What do you have installed and where?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'Are employees issued with unique cards or pin codes?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'Do you have an emergency power contingency plan in place?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Facility', 'Please describe the emergency power system and the amount of time of backup power provided.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Security Controls', 'Are security guards present at your facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Has an individual been assigned to manage incoming visitors?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Where is this person located?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Do procedures dictate that all incoming visitors confirm identity by examination of valid photo identification?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Are all visitors required to sign an NDA prior to entry into production areas?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Are all visitors always escorted throughout the facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Are visitors issued identification badges while onsite?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Do visitor badges provide access to production areas?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'Are logs used to capture incoming visitors?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'What information is being captured?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Visitor Management', 'How long are logs being kept?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Do you have CCTV cameras?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'How many cameras do you have?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Please list their locations.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Is footage date/time stamped?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'What frame rate is footage recorded at?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Do you use motion-activated recording?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Do you have any areas of poor lighting with CCTV cameras within your facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Is CCTV footage being retained?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Is the CCTV DVR restricted from access?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Are your CCTV cameras monitored?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Are camera cables hidden and access restricted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Is the camera system verified on a periodic basis?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'CCTV', 'Do you have any cameras with obstructed views?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Do you have an alarm system?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'What is the make and model of the system?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Does your alarm system have door prop alerts configured?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'After what period does the alarm trigger?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Does the alarm system support alerts via SMS or email?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Do you have alarm motion detectors within your facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Is your alarm connected to a central station, police station or in-house security team?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'How often is the alarm system checked?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Do you test the alarm by simulating a breach in physical security?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Are unique alarm codes issued to authorized personnel only?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Do you issue alarm codes to contractors or freelancers?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Alarm', 'Do you deactivate alarm codes when an employee leaves?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'Is electronic access control in place to all secure areas of the facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'Please list the areas protected by access control.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'Is there a list mapping individual to specific key cards/fobs?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'Is there a documented process in place for updating key card access or employee details?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'With what frequency is the access control list reviewed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'Which individual manages the access control list?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'What controls are in place with reference to third-party access to restricted areas?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic Access', 'Does the access control system provide an access log?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Access', 'How many entrance/exit points (including emergency escapes) does your facility have?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Access', 'Are they permanently locked?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Access', 'Do you hold physical keys?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Access', 'Are keys inventoried and accounted for on a regular basis?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Access', 'Where are unassigned keys stored?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Access', 'Do they override the electronic access control system?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Physical Access', 'What is your policy for lost or stolen keys (e.g., locks changed immediately)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Receiving', 'Is inbound content immediately inspected and validated against a work/shipping order?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Receiving', 'Is content immediately tagged, tracked (by an inventory or content management system) and stored securely?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Receiving', 'Is content labelled with a unique identifier (e.g., virtual or physical)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Receiving', 'Do you have a policy for receiving content out of normal working hours?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Receiving', 'Please describe the policy.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Receiving', 'Are couriers ever left unescorted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Are portable drives used to store or transport content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Is there a system in place to track all digital and physical assets associated with a project or show?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'What is the name(s) of tools used to track physical and digital assets within your facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'What is/are the purpose of these tools?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Does your content management system, inventory database, or order-entry system provide the ability to identify content as high security?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'How are "high-security" titles flagged in your system?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Are AKAs, Aliases, or Codenames used to ensure the confidentiality of working titles?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Does your facility share production space with another company?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Has the ability to access inventory databases, content management systems, or spreadsheets been restricted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Provide a description of individuals with the ability to access administrative function of your content management / inventory system.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Have policies regarding checking out physical assets been defined?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'What is your policy for checking out physical content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Are inventories performed on assets that contain content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'How often are these inventories performed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Is there a process in place to ensure that checked out content is returned within a defined timeframe?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Please describe this process.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Do you utilize a cloud application to manage pipeline workflow?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'Are movements of physical and digital content being tracked while in your facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Management Controls', 'What methods are used to assign ownership and a chain of custody at your facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Portable Hard Drives and Flash Drives', 'Do you use portable hard drives and/or flash drives to hold content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Portable Hard Drives and Flash Drives', 'Do the portable hard drives and/or flash drives provide hardware-based encryption?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Portable Hard Drives and Flash Drives', 'Do the portable hard drives and/or flash drives support AES with at least 128-bit key strength?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Portable Hard Drives and Flash Drives', 'What authentication methods do the portable hard drives and/or flash drives support?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Portable Hard Drives and Flash Drives', 'Do the portable hard drives and/or flash drives erase all content after multiple invalid authentication attempts?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Portable Hard Drives and Flash Drives', 'Are pin codes used to protect external hard drives?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shipping', 'Are all deliveries which occur inside the facility being tracked?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shipping', 'Are AKAs used on all packing slated for shipment?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shipping', 'Please describe situations where the actual title name is being used.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shipping', 'Are couriers ever allowed into restricted areas?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Are procedures in place to destroy rejected, damaged, and/or obsolete stock?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'What methods are used to destroy damaged stock?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Where are elements (e.g., check discs, test prints, mock-ups, ADR scripts) staged prior to destruction?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Have policies and procedures for Secure Destruction of Content been defined?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Please describe methods used to securely destroy/erase content residing on physical media.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Have policies and procedures for destroying finished elements (e.g., check discs, test prints, mock-ups, ADR scripts) been defined?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Please describe procedures for secure and timely destruction of finished elements.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Are third-party services used to securely destroy physical assets which are used for storing content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Please provide name and services provided by mentioned third-party companies.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Are services performed onsite?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Are certificates of destruction provided after completion of services?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Are records of each destruction of physical assets containing content tracked?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Secure Data Destruction', 'Where are disposals tracked and how long do the logs go back?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'Do you have a vault?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'How is access to the vault controlled?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'Do you have a safe on site?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'What is the weight of the safe and is it secured to the floor or wall?100lbs, yes', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'What is the fire rating of the safe?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'Do you have a secure segregated area dedicated for work on pre-theatrical content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'How is the area secured?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'Do employees have access to the safe/vault?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'Who has access to the safe/vault?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'Is the safe/vault locked when not in use?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vaults and Safes', 'What is your policy when an employee leaves who has safe/vault access?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wide Area Network (WAN) and Interoffice Connections', 'Do you have an up-to-date network and infrastructure diagram?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wide Area Network (WAN) and Interoffice Connections', 'Do you have any site-to-site network connections to other offices within the organization?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'How many firewalls are in place, and what is the brand and model of each firewall?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Are firewall rules configured to generate logs for all traffic?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Do you have a firewall policy?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Who is responsible for the firewall configuration?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Does the firewall policy permit traffic via IP, port and/or protocol?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'In general, what sort of protocols are permitted in and out of production environments?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Do you perform network penetration testing?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'How often are penetration tests conducted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Do you contract a third-party IT service provider?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'What services are provided by the third-party IT service provider?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Is the network penetration testing performed by this third-party IT provider?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Have policies around firewall management been defined?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Who is responsible for the management of the firewall?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Are security events configured to generate an alert?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Are there any additional security services running on the firewall (i.e. IDS, IPS, Network Antivirus, Web content filter etc.)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Is an IDS / IPS deployed for the Production network?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Are WAN connections segregated from internal network segments?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'How is the segregation implemented?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Is an email filtering solution in place?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'What email filter options have been configured?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Is a web content filtering solution in place?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'How is DNS implemented in your organization?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'What components does the DNS infrastructure comprise of?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'How many networks/VLANs do you have?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Please describe the function for each of them.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'How is each network segment segregated from each other? (i.e. physically, logically)', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'What devices / applications are hosted within the DMZ?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Please describe your firewall configuration controlling connections between the DMZ and your internal networks.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Firewall and Security Services', 'Do you use SNMP?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Do any workstations within the production networks have dual Network Interface Cards?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are there wireless NIC''s installed on production workstations?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'How are the wireless NIC''s, on editing workstations, disconnected?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Is there a policy in place for security configuration and system hardening?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are production workstations hardened?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Is there a screensaver configured on all workstations and servers?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'How long before the screensaver activates?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Does the Data IO Network have Antivirus services?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'What Antivirus service is installed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are the Antivirus DAT files manually or automatically updated?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'What is the date of the last installed update?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are active I/O devices present within the production environment?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are guest accounts removed/disabled from all production workstations/servers?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Is internet access available to workstations within the production environment?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are local firewalls configured on all production workstations/servers?Yes', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are laptops whole disk encrypted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Are the Production servers hardened?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'OS Hardening', 'Is there a policy regarding network appliance hardening?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Transfer Network', 'Do you have a network dedicated for content transfer with external/client systems?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Transfer Network', 'How is content received from or sent to external/client systems?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Transfer Network', 'How is content received by or sent from Production systems?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Transfer Network', 'How is network access between Production, Content Transfer and external/client networks restricted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Content Transfer Network', 'Do you maintain records of all externally accessible servers?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Change and Patch Management', 'Do you have a change management process?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Change and Patch Management', 'Please describe the process.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Change and Patch Management', 'Do you have a patch management process?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Change and Patch Management', 'Please describe the process.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vulnerability Assessment and Penetration Testing', 'Do you perform IT risk assessments / network penetration tests?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vulnerability Assessment and Penetration Testing', 'How often are the risk assessments / penetration tests performed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vulnerability Assessment and Penetration Testing', 'How soon are critical issues remediated?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vulnerability Assessment and Penetration Testing', 'Are vulnerability scans of external IP ranges and hosts performed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vulnerability Assessment and Penetration Testing', 'How often are the vulnerability scans performed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vulnerability Assessment and Penetration Testing', 'How soon are critical issues remediated? 24 hours or less', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Vulnerability Assessment and Penetration Testing', 'Has your organization subscribed to vulnerability notification services such as: OpenCVE (opencve.io) or NIST (nvd.nist.gov)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wireless Networks', 'Is there wireless access to Production network?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wireless Networks', 'Is the wireless access to Production network encrypted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wireless Networks', 'Is there wireless access to non-Production networks?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wireless Networks', 'Which non-Production networks are accessible via wireless networks?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wireless Networks', 'Do these non-Production wireless networks route users only to the intended non-Production networks?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Wireless Networks', 'Do SSIDs contain identifiable information such as company name and phone number?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Do production networks have access to the Internet?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'How do production networks access the Internet? (e.g., direct, Internet gateway system)', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Are there machines that are used to manage/ store /download content connected to the Internet?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Please describe the purpose of each machine.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Please describe all methods for ingesting client content into the production network. (i.e., via hardware encrypted hard drive, unidirectional ACLs between secure and insecure networks)', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Are hard drives used to shuttle content to and from the production network?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Has URL filtering been enabled for machines used to download and transmit content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Is the IT Network segmented to host like services (e.g., production vs. non-production) machines?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Has Inter-VLAN routing been established on the network?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Have protocols been defined to secure unused / open ports on Firewall(s) and Switching equipment?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Please describe make / model of network devices used to manage the network.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Production Network', 'Are any machines on the Production / Content network dual-homed with another network?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'What transfer tools are currently in use? Please describe the purpose of each.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Are any of these systems hosted and managed by your organization?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Is content scanned via anti-virus prior to ingest?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Please provide name of the anti-virus service.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Are assets deleted from content transfer / download machines after ingesting or delivery?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'On average, how long are assets kept on transfer / download machines until deleted?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Is there a central repository to store all delivered content sent to content transfer services or download machines?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Where is this content stored?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Are content transfer services and download machines hosted on a dedicated network segment?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Which network segment are they hosted on?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Are machines in this network segment restricted in accessing other networks?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Is there a process in place to monitor and approve all inbound and outbound content transfers?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Is content being encrypted when transferred to clients?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Do you maintain a web portal system to host content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Are user access reviews performed on Web portal systems used to manage content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Are web portal users assigned unique credentials?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Has a process been established to securely transmit passwords to end users?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Electronic File Transfer and Data I/O Network', 'Please describe the type of passwords used to encrypt content.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Does remote access into production environments currently exist?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'How is VPN / remote access managed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Please provide the names of services used.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Do remote / VPN services support multi-factor authentication?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Are IPSEC tunnels used to support point to point connections?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Please provide encryption algorithm used to secure these networks. 256AES', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Do non-production employees possess access to production environment(s)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Do full-time employees currently possess remote access into production environment(s)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Please provide title and purpose of remote access.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Do third-parties possess access to the production environment(s)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Please provide name of third-party and purpose of remote access.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Are there any remote systems used to access the network?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'What systems are used?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'Are the systems used personal or company provided?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Remote Access', 'How often are the end systems inspected?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Servers', 'Have policies been developed to manage server security?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Servers', 'Please describe current protocols.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Servers', 'Are servers and/or production systems hosted on third-party networks?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Servers', 'Have environmental controls been implemented in areas used to house servers, storage, LAN equipment and/or network devices?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'Please describe your shared storage solution used to store client assets/content. (i.e. NAS / SAN)', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'On what network is it located?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'What is the make, model, and capacity?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'Please describe controls that are in place to keep Marvel/Disney content segregated from other client assets and inaccessible to other clients? (i.e., separate volumes, directory permissions)', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'Please describe any redundancy measures in place on production storage.', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'Does the storage solution possess Internet access?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'What sort of filters / controls are in place to restrict this traffic to and from the internet?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'Does your storage solution store production and non-production assets?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'Has the storage architecture been documented?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Shared Storage / SAN', 'Does a hardening security guideline exist for shared storage?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'Are system logs enabled on network and system devices that store or transfer content?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'Are VPN logs reviewed on a periodic basis?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'How often are the logs reviewed?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'Have centralized logging services been established?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'Do you use a log management server or tool to manage logs across the network and system devices?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'Do you have a Security and Incident Event Management solution for aggregating and correlating logs for investigation purpose?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'Have alerts been established to notify security personnel of notable security events?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'System and Security Logging', 'How are security events communicated to security personnel?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Which network segments are using a directory service for centralized user, group and policy management (i.e., Active or Open Directory)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Are all production servers and shared storage platforms bound to the domain?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Are all production workstations (including Macs and Linux) bound to the domain?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Is Directory service used to enforce endpoint security policies such as password and mass storage device policy?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'What is the process for user account creation and access permission requests and changes (i.e., management review & approval processes)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'How often are accounts and access permissions reviewed to ensure that access which are no longer required are revoked in a timely manner?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Are third-party personnel provided user accounts configured to expire upon completion of contract/project?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Which users have administrative rights on production network equipment, servers, and workstations?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'How are administrative access rights managed and tracked?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'What process is in place to check all third-party accounts have expired?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Is there a policy prohibiting the sharing and e-mailing of passwords or user IDs?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Do you have a password policy?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'How are password policies enforced?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'What is the current password policy?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Are production systems configured for a screen saver timeout after a period of inactivity and require re-authentication to log back on?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'User Accounts and Passwords', 'Are user accounts locked out after a certain number of failed login attempts?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Workstations', 'How many production network workstations do you have?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Workstations', 'Which operating systems, versions and primary applications are being used (i.e. ProTools, Avid, Final Cut)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Workstations', 'Are sealed or tamper evident cases used for all workstations and servers that receive, send, manipulate, or store content in the production network?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Workstations', 'Do users have local administrative privileges on their own workstations?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Laptops', 'How many laptops are used in the facility?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Laptops', 'Which operating systems are being used?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Laptops', 'What are they used for?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Laptops', 'What client content is allowed to be accessed on, and / or stored on laptops?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Laptops', 'Do laptops have access to content (including the production network)?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Data Backup and Recovery', 'Do you have a backup and recovery policy for client data?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Data Backup and Recovery', 'Do you store client backup data offsite?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Data Backup and Recovery', 'Is a process in place to ensure only authorized administrators can access the backup location?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Data Backup and Recovery', 'Do all backup systems share the same administrator credentials?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Data Backup and Recovery', 'Are LTO tapes used for storing client backup data?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Data Backup and Recovery', 'Are the tapes securely wiped with 1-pass overwrite before they are reused?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Digital Asset Management (DAM)', 'Is there a standard system security policy enforced on DAM workstations?', 'radio', 'optional', current_timestamp, current_timestamp),
        (gen_random_uuid(), 'Digital Asset Management (DAM)', 'Is there a standard security policy enforced on DAM systems?', 'radio', 'optional', current_timestamp, current_timestamp);
