on:
  push:
    branches:
      - dev
      
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:nurdsoft/redesign-trust-portal-api.git"
          source_branch: "dev"
          destination_repo: "git@github.com:REDESIGNTeam/trust-portal-api.git"
          destination_branch: "dev"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}